version: '3.8'

services:
  # Extend the frontend service for development in VS Code
  frontend:
    # Use the existing Dockerfile.dev
    build:
      context: ..
      dockerfile: Dockerfile.dev

    # Override command to ensure the container keeps running
    command: /bin/bash -c "while sleep 1000; do :; done"

    # Additional volumes for development
    volumes:
      - ..:/app:cached
      - node_modules:/app/node_modules
      - next-cache:/app/.next

    # Environment for development
    environment:
      - NODE_ENV=development

    # Use the network from the main docker-compose.yml
    networks:
      - videohub-network

    # Ensure the container has enough resources
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

volumes:
  node_modules:
  next-cache:

networks:
  videohub-network:
    external: true
